### ISSUE TITLE
T7 - Etiquetado y procesado de datos

### ISSUE THREAD

**Issue by DavidCorreas** [AIVA2022TeamE/AIVA_2022-ImagenesAereas#13]
Preparar las imágenes del cliente para la utilización por el sistema.

- [ ] Segmentar calles
- [ ] Etiquetar coches
- [ ] Seccionar regiones

**Comment by elenagiraldo3** [comment]
Se ha decidido realizar una detección por filtros de color por lo que no será necesario realizar esta tarea
