### ISSUE TITLE
T8 - Calcular número de coches

### ISSUE THREAD

**Issue by DavidCorreas** [AIVA2022TeamE/AIVA_2022-ImagenesAereas#14]
Elección y entrenamiento de un modelo que tome las imágenes como entrada y devuelva el número de coches detectados en dichas imágenes.

- [ ] Elección de modelo
- [ ] Entrenamiento de modelo
- [ ] Comprobación de resultados

**Comment by juanma-mm** [comment]
Tiempo empleado: 2 semanas 
Tiempo estimado: 1 semana
