### ISSUE TITLE
T9 - Segmentación de la calle dentro de una imágen

### ISSUE THREAD

**Issue by DavidCorreas** [AIVA2022TeamE/AIVA_2022-ImagenesAereas#15]
Dada una imágen segmentar la calle desde la cual se detectarán los coches.

- [ ] Seleccionar la superficie de una calle dada una imagen
- [ ] Localización de la calle dada su nombre

**Comment by juanma-mm** [comment]
Tiempo empleado: 2 semanas 
Tiempo estimado: 1 semana
