### ISSUE TITLE
Documento de diseño

### ISSUE THREAD

**Issue by elenagiraldo3** [AIVA2022TeamE/AIVA_2022-ImagenesAereas#22]
Realización de un documento de diseño con los siguientes apartados.

-  Una sección "Introducción" que contenga:
> 1. Un párrafo introductorio al desarrollo realizado.
> 2. Una descripción del funcionamiento de los test sobre dos o tres ejemplos (incluyendo imágenes).
> 3. Un enlace al proyecto de GitHub.

- Una sección "Diseño de la solución" que contenga:
> 1. Un Diagrama UML Estático de Clases con las clases desarrolladas para hacer funcionar los algoritmos.
> 2. Un texto compuesto de varias secciones. Cada sección tendrá el título de una clase. En cada sección se explicará para qué sirve dicha clase utilizando un par de párrafos y señalando los métodos principales.
> 3. Un Diagrama UML de Secuencia con un ejemplo de uso de la aplicación y las clases involucradas.
> 4. Un texto explicando el diagrama de secuencia.
> 5. Secciones para los principales algoritmos desarrollados. Cada sección deberá incluir al menos un diagrama UML de Actividad con el algoritmo y un párrafo explicativo.

**Comment by juanma-mm** [comment]
Tiempo empleado: 1 semana 
Tiempo estimado: 1 semana
